name: BA Demo Setup CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  upload-bundle-stats:
    name: Upload Bundle Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: |
          npm install

      - name: Build and upload stats
        run: |
          npm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
